apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hermod-data
  namespace: hermod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName set by overlay (dev: hostpath, prod: microk8s-hostpath)
